using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CodeMapping.Tables
{
    public class CountryCodes : CodeTable
    {
        private static readonly List<CodeMapping> countryMappings = new List<CodeMapping>()
        {
            new CodeMapping() { ExternalCode = "af", InternalCode = "AFG", InternalKey = "004", Description = "Afghanistan" },
            new CodeMapping() { ExternalCode = "al", InternalCode = "ALB", InternalKey = "008", Description = "Albania" },
            new CodeMapping() { ExternalCode = "dz", InternalCode = "DZA", InternalKey = "012", Description = "Algeria" },
            new CodeMapping() { ExternalCode = "as", InternalCode = "ASM", InternalKey = "016", Description = "American Samoa" },
            new CodeMapping() { ExternalCode = "ad", InternalCode = "AND", InternalKey = "020", Description = "Andorra" },
            new CodeMapping() { ExternalCode = "ao", InternalCode = "AGO", InternalKey = "024", Description = "Angola" },
            new CodeMapping() { ExternalCode = "ai", InternalCode = "AIA", InternalKey = "660", Description = "Anguilla" },
            new CodeMapping() { ExternalCode = "aq", InternalCode = "ATA", InternalKey = "010", Description = "Antarctica" },
            new CodeMapping() { ExternalCode = "ag", InternalCode = "ATG", InternalKey = "028", Description = "Antigua and Barbuda" },
            new CodeMapping() { ExternalCode = "ar", InternalCode = "ARG", InternalKey = "032", Description = "Argentina" },
            new CodeMapping() { ExternalCode = "am", InternalCode = "ARM", InternalKey = "051", Description = "Armenia" },
            new CodeMapping() { ExternalCode = "aw", InternalCode = "ABW", InternalKey = "533", Description = "Aruba" },
            new CodeMapping() { ExternalCode = "au", InternalCode = "AUS", InternalKey = "036", Description = "Australia" },
            new CodeMapping() { ExternalCode = "at", InternalCode = "AUT", InternalKey = "040", Description = "Austria" },
            new CodeMapping() { ExternalCode = "az", InternalCode = "AZE", InternalKey = "031", Description = "Azerbaijan" },
            new CodeMapping() { ExternalCode = "bs", InternalCode = "BHS", InternalKey = "044", Description = "Bahamas (the)" },
            new CodeMapping() { ExternalCode = "bh", InternalCode = "BHR", InternalKey = "048", Description = "Bahrain" },
            new CodeMapping() { ExternalCode = "bd", InternalCode = "BGD", InternalKey = "050", Description = "Bangladesh" },
            new CodeMapping() { ExternalCode = "bb", InternalCode = "BRB", InternalKey = "052", Description = "Barbados" },
            new CodeMapping() { ExternalCode = "by", InternalCode = "BLR", InternalKey = "112", Description = "Belarus" },
            new CodeMapping() { ExternalCode = "be", InternalCode = "BEL", InternalKey = "056", Description = "Belgium" },
            new CodeMapping() { ExternalCode = "bz", InternalCode = "BLZ", InternalKey = "084", Description = "Belize" },
            new CodeMapping() { ExternalCode = "bj", InternalCode = "BEN", InternalKey = "204", Description = "Benin" },
            new CodeMapping() { ExternalCode = "bm", InternalCode = "BMU", InternalKey = "060", Description = "Bermuda" },
            new CodeMapping() { ExternalCode = "bt", InternalCode = "BTN", InternalKey = "064", Description = "Bhutan" },
            new CodeMapping() { ExternalCode = "bo", InternalCode = "BOL", InternalKey = "068", Description = "Bolivia (Plurinational State of)" },
            new CodeMapping() { ExternalCode = "bq", InternalCode = "BES", InternalKey = "535", Description = "Bonaire, Sint Eustatius and Saba" },
            new CodeMapping() { ExternalCode = "ba", InternalCode = "BIH", InternalKey = "070", Description = "Bosnia and Herzegovina" },
            new CodeMapping() { ExternalCode = "bw", InternalCode = "BWA", InternalKey = "072", Description = "Botswana" },
            new CodeMapping() { ExternalCode = "bv", InternalCode = "BVT", InternalKey = "074", Description = "Bouvet Island" },
            new CodeMapping() { ExternalCode = "br", InternalCode = "BRA", InternalKey = "076", Description = "Brazil" },
            new CodeMapping() { ExternalCode = "io", InternalCode = "IOT", InternalKey = "086", Description = "British Indian Ocean Territory (the)" },
            new CodeMapping() { ExternalCode = "bn", InternalCode = "BRN", InternalKey = "096", Description = "Brunei Darussalam" },
            new CodeMapping() { ExternalCode = "bg", InternalCode = "BGR", InternalKey = "100", Description = "Bulgaria" },
            new CodeMapping() { ExternalCode = "bf", InternalCode = "BFA", InternalKey = "854", Description = "Burkina Faso" },
            new CodeMapping() { ExternalCode = "bi", InternalCode = "BDI", InternalKey = "108", Description = "Burundi" },
            new CodeMapping() { ExternalCode = "cv", InternalCode = "CPV", InternalKey = "132", Description = "Cabo Verde" },
            new CodeMapping() { ExternalCode = "kh", InternalCode = "KHM", InternalKey = "116", Description = "Cambodia" },
            new CodeMapping() { ExternalCode = "cm", InternalCode = "CMR", InternalKey = "120", Description = "Cameroon" },
            new CodeMapping() { ExternalCode = "ca", InternalCode = "CAN", InternalKey = "124", Description = "Canada" },
            new CodeMapping() { ExternalCode = "ky", InternalCode = "CYM", InternalKey = "136", Description = "Cayman Islands (the)" },
            new CodeMapping() { ExternalCode = "cf", InternalCode = "CAF", InternalKey = "140", Description = "Central African Republic (the)" },
            new CodeMapping() { ExternalCode = "td", InternalCode = "TCD", InternalKey = "148", Description = "Chad" },
            new CodeMapping() { ExternalCode = "cl", InternalCode = "CHL", InternalKey = "152", Description = "Chile" },
            new CodeMapping() { ExternalCode = "cn", InternalCode = "CHN", InternalKey = "156", Description = "China" },
            new CodeMapping() { ExternalCode = "cx", InternalCode = "CXR", InternalKey = "162", Description = "Christmas Island" },
            new CodeMapping() { ExternalCode = "cc", InternalCode = "CCK", InternalKey = "166", Description = "Cocos (Keeling) Islands (the)" },
            new CodeMapping() { ExternalCode = "co", InternalCode = "COL", InternalKey = "170", Description = "Colombia" },
            new CodeMapping() { ExternalCode = "km", InternalCode = "COM", InternalKey = "174", Description = "Comoros (the)" },
            new CodeMapping() { ExternalCode = "cd", InternalCode = "COD", InternalKey = "180", Description = "Congo (the Democratic Republic of the)" },
            new CodeMapping() { ExternalCode = "cg", InternalCode = "COG", InternalKey = "178", Description = "Congo (the)" },
            new CodeMapping() { ExternalCode = "ck", InternalCode = "COK", InternalKey = "184", Description = "Cook Islands (the)" },
            new CodeMapping() { ExternalCode = "cr", InternalCode = "CRI", InternalKey = "188", Description = "Costa Rica" },
            new CodeMapping() { ExternalCode = "hr", InternalCode = "HRV", InternalKey = "191", Description = "Croatia" },
            new CodeMapping() { ExternalCode = "cu", InternalCode = "CUB", InternalKey = "192", Description = "Cuba" },
            new CodeMapping() { ExternalCode = "cw", InternalCode = "CUW", InternalKey = "531", Description = "Curaçao" },
            new CodeMapping() { ExternalCode = "cy", InternalCode = "CYP", InternalKey = "196", Description = "Cyprus" },
            new CodeMapping() { ExternalCode = "cz", InternalCode = "CZE", InternalKey = "203", Description = "Czechia" },
            new CodeMapping() { ExternalCode = "ci", InternalCode = "CIV", InternalKey = "384", Description = "Côte d'Ivoire" },
            new CodeMapping() { ExternalCode = "dk", InternalCode = "DNK", InternalKey = "208", Description = "Denmark" },
            new CodeMapping() { ExternalCode = "dj", InternalCode = "DJI", InternalKey = "262", Description = "Djibouti" },
            new CodeMapping() { ExternalCode = "dm", InternalCode = "DMA", InternalKey = "212", Description = "Dominica" },
            new CodeMapping() { ExternalCode = "do", InternalCode = "DOM", InternalKey = "214", Description = "Dominican Republic (the)" },
            new CodeMapping() { ExternalCode = "ec", InternalCode = "ECU", InternalKey = "218", Description = "Ecuador" },
            new CodeMapping() { ExternalCode = "eg", InternalCode = "EGY", InternalKey = "818", Description = "Egypt" },
            new CodeMapping() { ExternalCode = "sv", InternalCode = "SLV", InternalKey = "222", Description = "El Salvador" },
            new CodeMapping() { ExternalCode = "gq", InternalCode = "GNQ", InternalKey = "226", Description = "Equatorial Guinea" },
            new CodeMapping() { ExternalCode = "er", InternalCode = "ERI", InternalKey = "232", Description = "Eritrea" },
            new CodeMapping() { ExternalCode = "ee", InternalCode = "EST", InternalKey = "233", Description = "Estonia" },
            new CodeMapping() { ExternalCode = "sz", InternalCode = "SWZ", InternalKey = "748", Description = "Eswatini" },
            new CodeMapping() { ExternalCode = "et", InternalCode = "ETH", InternalKey = "231", Description = "Ethiopia" },
            new CodeMapping() { ExternalCode = "fk", InternalCode = "FLK", InternalKey = "238", Description = "Falkland Islands (the) [Malvinas]" },
            new CodeMapping() { ExternalCode = "fo", InternalCode = "FRO", InternalKey = "234", Description = "Faroe Islands (the)" },
            new CodeMapping() { ExternalCode = "fj", InternalCode = "FJI", InternalKey = "242", Description = "Fiji" },
            new CodeMapping() { ExternalCode = "fi", InternalCode = "FIN", InternalKey = "246", Description = "Finland" },
            new CodeMapping() { ExternalCode = "fr", InternalCode = "FRA", InternalKey = "250", Description = "France" },
            new CodeMapping() { ExternalCode = "gf", InternalCode = "GUF", InternalKey = "254", Description = "French Guiana" },
            new CodeMapping() { ExternalCode = "pf", InternalCode = "PYF", InternalKey = "258", Description = "French Polynesia" },
            new CodeMapping() { ExternalCode = "tf", InternalCode = "ATF", InternalKey = "260", Description = "French Southern Territories (the)" },
            new CodeMapping() { ExternalCode = "ga", InternalCode = "GAB", InternalKey = "266", Description = "Gabon" },
            new CodeMapping() { ExternalCode = "gm", InternalCode = "GMB", InternalKey = "270", Description = "Gambia (the)" },
            new CodeMapping() { ExternalCode = "ge", InternalCode = "GEO", InternalKey = "268", Description = "Georgia" },
            new CodeMapping() { ExternalCode = "de", InternalCode = "DEU", InternalKey = "276", Description = "Germany" },
            new CodeMapping() { ExternalCode = "gh", InternalCode = "GHA", InternalKey = "288", Description = "Ghana" },
            new CodeMapping() { ExternalCode = "gi", InternalCode = "GIB", InternalKey = "292", Description = "Gibraltar" },
            new CodeMapping() { ExternalCode = "gr", InternalCode = "GRC", InternalKey = "300", Description = "Greece" },
            new CodeMapping() { ExternalCode = "gl", InternalCode = "GRL", InternalKey = "304", Description = "Greenland" },
            new CodeMapping() { ExternalCode = "gd", InternalCode = "GRD", InternalKey = "308", Description = "Grenada" },
            new CodeMapping() { ExternalCode = "gp", InternalCode = "GLP", InternalKey = "312", Description = "Guadeloupe" },
            new CodeMapping() { ExternalCode = "gu", InternalCode = "GUM", InternalKey = "316", Description = "Guam" },
            new CodeMapping() { ExternalCode = "gt", InternalCode = "GTM", InternalKey = "320", Description = "Guatemala" },
            new CodeMapping() { ExternalCode = "gg", InternalCode = "GGY", InternalKey = "831", Description = "Guernsey" },
            new CodeMapping() { ExternalCode = "gn", InternalCode = "GIN", InternalKey = "324", Description = "Guinea" },
            new CodeMapping() { ExternalCode = "gw", InternalCode = "GNB", InternalKey = "624", Description = "Guinea-Bissau" },
            new CodeMapping() { ExternalCode = "gy", InternalCode = "GUY", InternalKey = "328", Description = "Guyana" },
            new CodeMapping() { ExternalCode = "ht", InternalCode = "HTI", InternalKey = "332", Description = "Haiti" },
            new CodeMapping() { ExternalCode = "hm", InternalCode = "HMD", InternalKey = "334", Description = "Heard Island and McDonald Islands" },
            new CodeMapping() { ExternalCode = "va", InternalCode = "VAT", InternalKey = "336", Description = "Holy See (the)" },
            new CodeMapping() { ExternalCode = "hn", InternalCode = "HND", InternalKey = "340", Description = "Honduras" },
            new CodeMapping() { ExternalCode = "hk", InternalCode = "HKG", InternalKey = "344", Description = "Hong Kong" },
            new CodeMapping() { ExternalCode = "hu", InternalCode = "HUN", InternalKey = "348", Description = "Hungary" },
            new CodeMapping() { ExternalCode = "is", InternalCode = "ISL", InternalKey = "352", Description = "Iceland" },
            new CodeMapping() { ExternalCode = "in", InternalCode = "IND", InternalKey = "356", Description = "India" },
            new CodeMapping() { ExternalCode = "id", InternalCode = "IDN", InternalKey = "360", Description = "Indonesia" },
            new CodeMapping() { ExternalCode = "ir", InternalCode = "IRN", InternalKey = "364", Description = "Iran (Islamic Republic of)" },
            new CodeMapping() { ExternalCode = "iq", InternalCode = "IRQ", InternalKey = "368", Description = "Iraq" },
            new CodeMapping() { ExternalCode = "ie", InternalCode = "IRL", InternalKey = "372", Description = "Ireland" },
            new CodeMapping() { ExternalCode = "im", InternalCode = "IMN", InternalKey = "833", Description = "Isle of Man" },
            new CodeMapping() { ExternalCode = "il", InternalCode = "ISR", InternalKey = "376", Description = "Israel" },
            new CodeMapping() { ExternalCode = "it", InternalCode = "ITA", InternalKey = "380", Description = "Italy" },
            new CodeMapping() { ExternalCode = "jm", InternalCode = "JAM", InternalKey = "388", Description = "Jamaica" },
            new CodeMapping() { ExternalCode = "jp", InternalCode = "JPN", InternalKey = "392", Description = "Japan" },
            new CodeMapping() { ExternalCode = "je", InternalCode = "JEY", InternalKey = "832", Description = "Jersey" },
            new CodeMapping() { ExternalCode = "jo", InternalCode = "JOR", InternalKey = "400", Description = "Jordan" },
            new CodeMapping() { ExternalCode = "kz", InternalCode = "KAZ", InternalKey = "398", Description = "Kazakhstan" },
            new CodeMapping() { ExternalCode = "ke", InternalCode = "KEN", InternalKey = "404", Description = "Kenya" },
            new CodeMapping() { ExternalCode = "ki", InternalCode = "KIR", InternalKey = "296", Description = "Kiribati" },
            new CodeMapping() { ExternalCode = "kp", InternalCode = "PRK", InternalKey = "408", Description = "Korea (the Democratic People's Republic of)" },
            new CodeMapping() { ExternalCode = "kr", InternalCode = "KOR", InternalKey = "410", Description = "Korea (the Republic of)" },
            new CodeMapping() { ExternalCode = "kw", InternalCode = "KWT", InternalKey = "414", Description = "Kuwait" },
            new CodeMapping() { ExternalCode = "kg", InternalCode = "KGZ", InternalKey = "417", Description = "Kyrgyzstan" },
            new CodeMapping() { ExternalCode = "la", InternalCode = "LAO", InternalKey = "418", Description = "Lao People's Democratic Republic (the)" },
            new CodeMapping() { ExternalCode = "lv", InternalCode = "LVA", InternalKey = "428", Description = "Latvia" },
            new CodeMapping() { ExternalCode = "lb", InternalCode = "LBN", InternalKey = "422", Description = "Lebanon" },
            new CodeMapping() { ExternalCode = "ls", InternalCode = "LSO", InternalKey = "426", Description = "Lesotho" },
            new CodeMapping() { ExternalCode = "lr", InternalCode = "LBR", InternalKey = "430", Description = "Liberia" },
            new CodeMapping() { ExternalCode = "ly", InternalCode = "LBY", InternalKey = "434", Description = "Libya" },
            new CodeMapping() { ExternalCode = "li", InternalCode = "LIE", InternalKey = "438", Description = "Liechtenstein" },
            new CodeMapping() { ExternalCode = "lt", InternalCode = "LTU", InternalKey = "440", Description = "Lithuania" },
            new CodeMapping() { ExternalCode = "lu", InternalCode = "LUX", InternalKey = "442", Description = "Luxembourg" },
            new CodeMapping() { ExternalCode = "mo", InternalCode = "MAC", InternalKey = "446", Description = "Macao" },
            new CodeMapping() { ExternalCode = "mg", InternalCode = "MDG", InternalKey = "450", Description = "Madagascar" },
            new CodeMapping() { ExternalCode = "mw", InternalCode = "MWI", InternalKey = "454", Description = "Malawi" },
            new CodeMapping() { ExternalCode = "my", InternalCode = "MYS", InternalKey = "458", Description = "Malaysia" },
            new CodeMapping() { ExternalCode = "mv", InternalCode = "MDV", InternalKey = "462", Description = "Maldives" },
            new CodeMapping() { ExternalCode = "ml", InternalCode = "MLI", InternalKey = "466", Description = "Mali" },
            new CodeMapping() { ExternalCode = "mt", InternalCode = "MLT", InternalKey = "470", Description = "Malta" },
            new CodeMapping() { ExternalCode = "mh", InternalCode = "MHL", InternalKey = "584", Description = "Marshall Islands (the)" },
            new CodeMapping() { ExternalCode = "mq", InternalCode = "MTQ", InternalKey = "474", Description = "Martinique" },
            new CodeMapping() { ExternalCode = "mr", InternalCode = "MRT", InternalKey = "478", Description = "Mauritania" },
            new CodeMapping() { ExternalCode = "mu", InternalCode = "MUS", InternalKey = "480", Description = "Mauritius" },
            new CodeMapping() { ExternalCode = "yt", InternalCode = "MYT", InternalKey = "175", Description = "Mayotte" },
            new CodeMapping() { ExternalCode = "mx", InternalCode = "MEX", InternalKey = "484", Description = "Mexico" },
            new CodeMapping() { ExternalCode = "fm", InternalCode = "FSM", InternalKey = "583", Description = "Micronesia (Federated States of)" },
            new CodeMapping() { ExternalCode = "md", InternalCode = "MDA", InternalKey = "498", Description = "Moldova (the Republic of)" },
            new CodeMapping() { ExternalCode = "mc", InternalCode = "MCO", InternalKey = "492", Description = "Monaco" },
            new CodeMapping() { ExternalCode = "mn", InternalCode = "MNG", InternalKey = "496", Description = "Mongolia" },
            new CodeMapping() { ExternalCode = "me", InternalCode = "MNE", InternalKey = "499", Description = "Montenegro" },
            new CodeMapping() { ExternalCode = "ms", InternalCode = "MSR", InternalKey = "500", Description = "Montserrat" },
            new CodeMapping() { ExternalCode = "ma", InternalCode = "MAR", InternalKey = "504", Description = "Morocco" },
            new CodeMapping() { ExternalCode = "mz", InternalCode = "MOZ", InternalKey = "508", Description = "Mozambique" },
            new CodeMapping() { ExternalCode = "mm", InternalCode = "MMR", InternalKey = "104", Description = "Myanmar" },
            new CodeMapping() { ExternalCode = "na", InternalCode = "NAM", InternalKey = "516", Description = "Namibia" },
            new CodeMapping() { ExternalCode = "nr", InternalCode = "NRU", InternalKey = "520", Description = "Nauru" },
            new CodeMapping() { ExternalCode = "np", InternalCode = "NPL", InternalKey = "524", Description = "Nepal" },
            new CodeMapping() { ExternalCode = "nl", InternalCode = "NLD", InternalKey = "528", Description = "Netherlands (the)" },
            new CodeMapping() { ExternalCode = "nc", InternalCode = "NCL", InternalKey = "540", Description = "New Caledonia" },
            new CodeMapping() { ExternalCode = "nz", InternalCode = "NZL", InternalKey = "554", Description = "New Zealand" },
            new CodeMapping() { ExternalCode = "ni", InternalCode = "NIC", InternalKey = "558", Description = "Nicaragua" },
            new CodeMapping() { ExternalCode = "ne", InternalCode = "NER", InternalKey = "562", Description = "Niger (the)" },
            new CodeMapping() { ExternalCode = "ng", InternalCode = "NGA", InternalKey = "566", Description = "Nigeria" },
            new CodeMapping() { ExternalCode = "nu", InternalCode = "NIU", InternalKey = "570", Description = "Niue" },
            new CodeMapping() { ExternalCode = "nf", InternalCode = "NFK", InternalKey = "574", Description = "Norfolk Island" },
            new CodeMapping() { ExternalCode = "mp", InternalCode = "MNP", InternalKey = "580", Description = "Northern Mariana Islands (the)" },
            new CodeMapping() { ExternalCode = "no", InternalCode = "NOR", InternalKey = "578", Description = "Norway" },
            new CodeMapping() { ExternalCode = "om", InternalCode = "OMN", InternalKey = "512", Description = "Oman" },
            new CodeMapping() { ExternalCode = "pk", InternalCode = "PAK", InternalKey = "586", Description = "Pakistan" },
            new CodeMapping() { ExternalCode = "pw", InternalCode = "PLW", InternalKey = "585", Description = "Palau" },
            new CodeMapping() { ExternalCode = "ps", InternalCode = "PSE", InternalKey = "275", Description = "Palestine, State of" },
            new CodeMapping() { ExternalCode = "pa", InternalCode = "PAN", InternalKey = "591", Description = "Panama" },
            new CodeMapping() { ExternalCode = "pg", InternalCode = "PNG", InternalKey = "598", Description = "Papua New Guinea" },
            new CodeMapping() { ExternalCode = "py", InternalCode = "PRY", InternalKey = "600", Description = "Paraguay" },
            new CodeMapping() { ExternalCode = "pe", InternalCode = "PER", InternalKey = "604", Description = "Peru" },
            new CodeMapping() { ExternalCode = "ph", InternalCode = "PHL", InternalKey = "608", Description = "Philippines (the)" },
            new CodeMapping() { ExternalCode = "pn", InternalCode = "PCN", InternalKey = "612", Description = "Pitcairn" },
            new CodeMapping() { ExternalCode = "pl", InternalCode = "POL", InternalKey = "616", Description = "Poland" },
            new CodeMapping() { ExternalCode = "pt", InternalCode = "PRT", InternalKey = "620", Description = "Portugal" },
            new CodeMapping() { ExternalCode = "pr", InternalCode = "PRI", InternalKey = "630", Description = "Puerto Rico" },
            new CodeMapping() { ExternalCode = "qa", InternalCode = "QAT", InternalKey = "634", Description = "Qatar" },
            new CodeMapping() { ExternalCode = "mk", InternalCode = "MKD", InternalKey = "807", Description = "Republic of North Macedonia" },
            new CodeMapping() { ExternalCode = "ro", InternalCode = "ROU", InternalKey = "642", Description = "Romania" },
            new CodeMapping() { ExternalCode = "ru", InternalCode = "RUS", InternalKey = "643", Description = "Russian Federation (the)" },
            new CodeMapping() { ExternalCode = "rw", InternalCode = "RWA", InternalKey = "646", Description = "Rwanda" },
            new CodeMapping() { ExternalCode = "re", InternalCode = "REU", InternalKey = "638", Description = "Réunion" },
            new CodeMapping() { ExternalCode = "bl", InternalCode = "BLM", InternalKey = "652", Description = "Saint Barthélemy" },
            new CodeMapping() { ExternalCode = "sh", InternalCode = "SHN", InternalKey = "654", Description = "Saint Helena, Ascension and Tristan da Cunha" },
            new CodeMapping() { ExternalCode = "kn", InternalCode = "KNA", InternalKey = "659", Description = "Saint Kitts and Nevis" },
            new CodeMapping() { ExternalCode = "lc", InternalCode = "LCA", InternalKey = "662", Description = "Saint Lucia" },
            new CodeMapping() { ExternalCode = "mf", InternalCode = "MAF", InternalKey = "663", Description = "Saint Martin (French part)" },
            new CodeMapping() { ExternalCode = "pm", InternalCode = "SPM", InternalKey = "666", Description = "Saint Pierre and Miquelon" },
            new CodeMapping() { ExternalCode = "vc", InternalCode = "VCT", InternalKey = "670", Description = "Saint Vincent and the Grenadines" },
            new CodeMapping() { ExternalCode = "ws", InternalCode = "WSM", InternalKey = "882", Description = "Samoa" },
            new CodeMapping() { ExternalCode = "sm", InternalCode = "SMR", InternalKey = "674", Description = "San Marino" },
            new CodeMapping() { ExternalCode = "st", InternalCode = "STP", InternalKey = "678", Description = "Sao Tome and Principe" },
            new CodeMapping() { ExternalCode = "sa", InternalCode = "SAU", InternalKey = "682", Description = "Saudi Arabia" },
            new CodeMapping() { ExternalCode = "sn", InternalCode = "SEN", InternalKey = "686", Description = "Senegal" },
            new CodeMapping() { ExternalCode = "rs", InternalCode = "SRB", InternalKey = "688", Description = "Serbia" },
            new CodeMapping() { ExternalCode = "sc", InternalCode = "SYC", InternalKey = "690", Description = "Seychelles" },
            new CodeMapping() { ExternalCode = "sl", InternalCode = "SLE", InternalKey = "694", Description = "Sierra Leone" },
            new CodeMapping() { ExternalCode = "sg", InternalCode = "SGP", InternalKey = "702", Description = "Singapore" },
            new CodeMapping() { ExternalCode = "sx", InternalCode = "SXM", InternalKey = "534", Description = "Sint Maarten (Dutch part)" },
            new CodeMapping() { ExternalCode = "sk", InternalCode = "SVK", InternalKey = "703", Description = "Slovakia" },
            new CodeMapping() { ExternalCode = "si", InternalCode = "SVN", InternalKey = "705", Description = "Slovenia" },
            new CodeMapping() { ExternalCode = "sb", InternalCode = "SLB", InternalKey = "090", Description = "Solomon Islands" },
            new CodeMapping() { ExternalCode = "so", InternalCode = "SOM", InternalKey = "706", Description = "Somalia" },
            new CodeMapping() { ExternalCode = "za", InternalCode = "ZAF", InternalKey = "710", Description = "South Africa" },
            new CodeMapping() { ExternalCode = "gs", InternalCode = "SGS", InternalKey = "239", Description = "South Georgia and the South Sandwich Islands" },
            new CodeMapping() { ExternalCode = "ss", InternalCode = "SSD", InternalKey = "728", Description = "South Sudan" },
            new CodeMapping() { ExternalCode = "es", InternalCode = "ESP", InternalKey = "724", Description = "Spain" },
            new CodeMapping() { ExternalCode = "lk", InternalCode = "LKA", InternalKey = "144", Description = "Sri Lanka" },
            new CodeMapping() { ExternalCode = "sd", InternalCode = "SDN", InternalKey = "729", Description = "Sudan (the)" },
            new CodeMapping() { ExternalCode = "sr", InternalCode = "SUR", InternalKey = "740", Description = "Suriname" },
            new CodeMapping() { ExternalCode = "sj", InternalCode = "SJM", InternalKey = "744", Description = "Svalbard and Jan Mayen" },
            new CodeMapping() { ExternalCode = "se", InternalCode = "SWE", InternalKey = "752", Description = "Sweden" },
            new CodeMapping() { ExternalCode = "ch", InternalCode = "CHE", InternalKey = "756", Description = "Switzerland" },
            new CodeMapping() { ExternalCode = "sy", InternalCode = "SYR", InternalKey = "760", Description = "Syrian Arab Republic" },
            new CodeMapping() { ExternalCode = "tw", InternalCode = "TWN", InternalKey = "158", Description = "Taiwan (Province of China)" },
            new CodeMapping() { ExternalCode = "tj", InternalCode = "TJK", InternalKey = "762", Description = "Tajikistan" },
            new CodeMapping() { ExternalCode = "tz", InternalCode = "TZA", InternalKey = "834", Description = "Tanzania, United Republic of" },
            new CodeMapping() { ExternalCode = "th", InternalCode = "THA", InternalKey = "764", Description = "Thailand" },
            new CodeMapping() { ExternalCode = "tl", InternalCode = "TLS", InternalKey = "626", Description = "Timor-Leste" },
            new CodeMapping() { ExternalCode = "tg", InternalCode = "TGO", InternalKey = "768", Description = "Togo" },
            new CodeMapping() { ExternalCode = "tk", InternalCode = "TKL", InternalKey = "772", Description = "Tokelau" },
            new CodeMapping() { ExternalCode = "to", InternalCode = "TON", InternalKey = "776", Description = "Tonga" },
            new CodeMapping() { ExternalCode = "tt", InternalCode = "TTO", InternalKey = "780", Description = "Trinidad and Tobago" },
            new CodeMapping() { ExternalCode = "tn", InternalCode = "TUN", InternalKey = "788", Description = "Tunisia" },
            new CodeMapping() { ExternalCode = "tr", InternalCode = "TUR", InternalKey = "792", Description = "Turkey" },
            new CodeMapping() { ExternalCode = "tm", InternalCode = "TKM", InternalKey = "795", Description = "Turkmenistan" },
            new CodeMapping() { ExternalCode = "tc", InternalCode = "TCA", InternalKey = "796", Description = "Turks and Caicos Islands (the)" },
            new CodeMapping() { ExternalCode = "tv", InternalCode = "TUV", InternalKey = "798", Description = "Tuvalu" },
            new CodeMapping() { ExternalCode = "ug", InternalCode = "UGA", InternalKey = "800", Description = "Uganda" },
            new CodeMapping() { ExternalCode = "ua", InternalCode = "UKR", InternalKey = "804", Description = "Ukraine" },
            new CodeMapping() { ExternalCode = "ae", InternalCode = "ARE", InternalKey = "784", Description = "United Arab Emirates (the)" },
            new CodeMapping() { ExternalCode = "gb", InternalCode = "GBR", InternalKey = "826", Description = "United Kingdom of Great Britain and Northern Ireland (the)" },
            new CodeMapping() { ExternalCode = "um", InternalCode = "UMI", InternalKey = "581", Description = "United States Minor Outlying Islands (the)" },
            new CodeMapping() { ExternalCode = "us", InternalCode = "USA", InternalKey = "840", Description = "United States of America (the)" },
            new CodeMapping() { ExternalCode = "uy", InternalCode = "URY", InternalKey = "858", Description = "Uruguay" },
            new CodeMapping() { ExternalCode = "uz", InternalCode = "UZB", InternalKey = "860", Description = "Uzbekistan" },
            new CodeMapping() { ExternalCode = "vu", InternalCode = "VUT", InternalKey = "548", Description = "Vanuatu" },
            new CodeMapping() { ExternalCode = "ve", InternalCode = "VEN", InternalKey = "862", Description = "Venezuela (Bolivarian Republic of)" },
            new CodeMapping() { ExternalCode = "vn", InternalCode = "VNM", InternalKey = "704", Description = "Viet Nam" },
            new CodeMapping() { ExternalCode = "vg", InternalCode = "VGB", InternalKey = "092", Description = "Virgin Islands (British)" },
            new CodeMapping() { ExternalCode = "vi", InternalCode = "VIR", InternalKey = "850", Description = "Virgin Islands (U.S.)" },
            new CodeMapping() { ExternalCode = "wf", InternalCode = "WLF", InternalKey = "876", Description = "Wallis and Futuna" },
            new CodeMapping() { ExternalCode = "eh", InternalCode = "ESH", InternalKey = "732", Description = "Western Sahara" },
            new CodeMapping() { ExternalCode = "ye", InternalCode = "YEM", InternalKey = "887", Description = "Yemen" },
            new CodeMapping() { ExternalCode = "zm", InternalCode = "ZMB", InternalKey = "894", Description = "Zambia" },
            new CodeMapping() { ExternalCode = "zw", InternalCode = "ZWE", InternalKey = "716", Description = "Zimbabwe" },
            new CodeMapping() { ExternalCode = "ax", InternalCode = "ALA", InternalKey = "248", Description = "Åland Islands" }
        };

        protected override List<CodeMapping> Mappings { get { return countryMappings; } }
    }
}
